import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';
import { Search } from 'lucide-react';

interface DetectionResult { score: number; label: string; }

// Simplified SynthID watermark detector inspired by the open-source
// synthid-text project. This is **not** the official algorithm but
// provides a heuristic indication of possible watermark patterns.
const detectSynthIDWatermark = (text: string): number => {
  const tokens = text.trim().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return 0;
  const hashed = tokens.map((t) =>
    t
      .split("")
      .reduce((acc, c) => acc + c.charCodeAt(0), 0) % 2,
  );
  const ones = hashed.filter((h) => h === 1).length;
  const zeros = hashed.length - ones;
  const ratio = Math.max(ones, zeros) / hashed.length;
  return ratio;
};

const analyzeText = (text: string): DetectionResult => {
  const words = text.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return { score: 0, label: 'No text provided' };
  const uniqueRatio = new Set(words).size / words.length;
  let score = 0;
  if (uniqueRatio < 0.5 || uniqueRatio > 0.95) score += 0.3;
  if (/as an ai language model/i.test(text)) score += 0.7;
  if (/(\b\w{3,}\b)(\s+\1){2,}/i.test(text)) score += 0.3;
  const synthScore = detectSynthIDWatermark(text);
  score += synthScore * 0.5;
  if (score > 1) score = 1;
  const label = score > 0.7 ? 'Likely AI-generated' : score > 0.4 ? 'Possibly AI-generated' : 'Likely Human-written';
  return { score, label };
};

const AIContentDetector = () => {
  const { toast } = useToast();
  const [text, setText] = useState('');
  const [result, setResult] = useState<DetectionResult | null>(null);

  const handleAnalyze = () => {
    const res = analyzeText(text);
    setResult(res);
    toast({ title: 'Detection complete', description: res.label });
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      setText(content);
    };
    reader.readAsText(file);
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center gap-2">
          <Search className="h-5 w-5 text-primary" />
          <CardTitle>AI Content Detector</CardTitle>
        </div>
        <CardDescription>Analyze text to determine if it may have been generated by AI.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <Textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Paste text here"
          className="min-h-[150px]"
        />
        <input
          type="file"
          accept=".txt,.md,.json,.csv,.log,.html,.js,.ts,.tsx,.py,.java,.pdf,.docx"
          onChange={handleFileUpload}
        />
        <Button onClick={handleAnalyze}>Analyze</Button>
        {result && (
          <div className="space-y-2">
            <Progress value={result.score * 100} />
            <p className="text-sm text-muted-foreground">
              {result.label} ({Math.round(result.score * 100)}%)
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default AIContentDetector;
