/* -------------------------------------------------------------------------- */
/*  REAL DATA  – parsed from trimed_estimated_tokens_2022_2024.csv            */
/*  (values shown are trillions of tokens per month, Jan-24 ➜ Dec-24)         */
/* -------------------------------------------------------------------------- */
export const companyStats: CompanyStatType[] = [
  {
    name: "Microsoft",
    ceo: "Satya Nadella",
    position: "Chairman & CEO",
    aiFocusArea:
      "Large-scale cloud AI infrastructure and integrated AI assistants",
    flagshipAIProduct: "Azure AI / Microsoft Copilot",
    estimatedTokens: "≈ 80 Trillion tokens / month", // Dec-24
    tokenHistory: [
      { month: "Jan 24", tokens: 58 },
      { month: "Feb 24", tokens: 60 },
      { month: "Mar 24", tokens: 62 },
      { month: "Apr 24", tokens: 64 },
      { month: "May 24", tokens: 66 },
      { month: "Jun 24", tokens: 68 },
      { month: "Jul 24", tokens: 70 },
      { month: "Aug 24", tokens: 72 },
      { month: "Sep 24", tokens: 74 },
      { month: "Oct 24", tokens: 76 },
      { month: "Nov 24", tokens: 78 },
      { month: "Dec 24", tokens: 80 },
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/MS-Exec-Nadella-Satya-2017-08-31-22_%28cropped%29.jpg/250px-MS-Exec-Nadella-Satya-2017-08-31-22_%28cropped%29.jpg",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1024px-Microsoft_logo.svg.png",
    color: "from-blue-600 to-sky-500",
    gradientId: "msftGradient",
    foundedYear: 1975,
    headquarters: "Redmond, Washington, USA",
  },
  {
    name: "Amazon",
    ceo: "Jeff Bezos",
    position: "Executive Chairman",
    aiFocusArea: "Cloud AI services, e-commerce AI, and voice assistants",
    flagshipAIProduct: "AWS Bedrock / Alexa",
    estimatedTokens: "≈ 25 Trillion tokens / month",
    tokenHistory: [
      { month: "Jan 24", tokens: 18.09 },
      { month: "Feb 24", tokens: 18.71 },
      { month: "Mar 24", tokens: 19.34 },
      { month: "Apr 24", tokens: 19.97 },
      { month: "May 24", tokens: 20.60 },
      { month: "Jun 24", tokens: 21.26 },
      { month: "Jul 24", tokens: 21.86 },
      { month: "Aug 24", tokens: 22.49 },
      { month: "Sep 24", tokens: 23.11 },
      { month: "Oct 24", tokens: 23.74 },
      { month: "Nov 24", tokens: 24.37 },
      { month: "Dec 24", tokens: 25.00 },
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Jeff_Bezos_visits_LAAFB_SMC_%283908618%29_%28cropped%29.jpeg/250px-Jeff_Bezos_visits_LAAFB_SMC_%283908618%29_%28cropped%29.jpeg",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1024px-Amazon_logo.svg.png",
    color: "from-orange-500 to-yellow-400",
    gradientId: "amznGradient",
    foundedYear: 1994,
    headquarters: "Seattle, Washington, USA",
  },
  {
    name: "OpenAI",
    ceo: "Sam Altman",
    position: "CEO",
    aiFocusArea: "Pioneering large language models and generative-AI research",
    flagshipAIProduct: "ChatGPT / GPT-4o",
    estimatedTokens: "≈ 28 Trillion tokens / month",
    tokenHistory: [
      { month: "Jan 24", tokens: 19.51 },
      { month: "Feb 24", tokens: 20.29 },
      { month: "Mar 24", tokens: 21.06 },
      { month: "Apr 24", tokens: 21.83 },
      { month: "May 24", tokens: 22.60 },
      { month: "Jun 24", tokens: 23.37 },
      { month: "Jul 24", tokens: 24.11 },
      { month: "Aug 24", tokens: 24.91 },
      { month: "Sep 24", tokens: 25.69 },
      { month: "Oct 24", tokens: 26.46 },
      { month: "Nov 24", tokens: 27.23 },
      { month: "Dec 24", tokens: 28.00 },
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sam_Altman_TechCrunch_SF_2019_Day_2_Oct_3_%28cropped%29.jpg/250px-Sam_Altman_TechCrunch_SF_2019_Day_2_Oct_3_%28cropped%29.jpg",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/1024px-OpenAI_Logo.svg.png",
    color: "from-teal-500 to-emerald-500",
    gradientId: "oaiGradient",
    foundedYear: 2015,
    headquarters: "San Francisco, California, USA",
  },
  {
    name: "Google",
    ceo: "Sundar Pichai",
    position: "CEO",
    aiFocusArea:
      "Leading AI research, cloud-AI platform, and integrated AI features",
    flagshipAIProduct: "Gemini / Vertex AI",
    estimatedTokens: "≈ 100 Trillion tokens / month",
    tokenHistory: [
      { month: "Jan 24", tokens: 73.29 },
      { month: "Feb 24", tokens: 75.71 },
      { month: "Mar 24", tokens: 78.14 },
      { month: "Apr 24", tokens: 80.57 },
      { month: "May 24", tokens: 83.00 },
      { month: "Jun 24", tokens: 85.43 },
      { month: "Jul 24", tokens: 87.86 },
      { month: "Aug 24", tokens: 90.29 },
      { month: "Sep 24", tokens: 92.71 },
      { month: "Oct 24", tokens: 95.14 },
      { month: "Nov 24", tokens: 97.57 },
      { month: "Dec 24", tokens: 100.00 },
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Sundar_Pichai_-_2023_%28cropped%29.jpg/250px-Sundar_Pichai_-_2023_%28cropped%29.jpg",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1024px-Google_2015_logo.svg.png",
    color: "from-red-500 to-blue-500",
    gradientId: "googGradient",
    foundedYear: 1998,
    headquarters: "Mountain View, California, USA",
  },
  {
    name: "Meta",
    ceo: "Mark Zuckerberg",
    position: "Chairman & CEO",
    aiFocusArea:
      "Open-source AI models and AI for social media and the metaverse",
    flagshipAIProduct: "Llama 3 / Meta AI",
    estimatedTokens: "≈ 8 Trillion tokens / month",
    tokenHistory: [
      { month: "Jan 24", tokens: 5.8 },
      { month: "Feb 24", tokens: 6.0 },
      { month: "Mar 24", tokens: 6.2 },
      { month: "Apr 24", tokens: 6.4 },
      { month: "May 24", tokens: 6.6 },
      { month: "Jun 24", tokens: 6.8 },
      { month: "Jul 24", tokens: 7.0 },
      { month: "Aug 24", tokens: 7.2 },
      { month: "Sep 24", tokens: 7.4 },
      { month: "Oct 24", tokens: 7.6 },
      { month: "Nov 24", tokens: 7.8 },
      { month: "Dec 24", tokens: 8.0 },
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg/1280px-Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png",
    color: "from-blue-700 to-indigo-600",
    gradientId: "metaGradient",
    foundedYear: 2004,
    headquarters: "Menlo Park, California, USA",
  },
  {
    name: "Anthropic",
    ceo: "Dario Amodei",
    position: "CEO",
    aiFocusArea: "AI safety and constitutional-AI principles",
    flagshipAIProduct: "Claude 3 (Opus)",
    estimatedTokens: "≈ 12 Trillion tokens / month",
    tokenHistory: [
      { month: "Jan 24", tokens: 8.29 },
      { month: "Feb 24", tokens: 8.63 },
      { month: "Mar 24", tokens: 8.97 },
      { month: "Apr 24", tokens: 9.30 },
      { month: "May 24", tokens: 9.64 },
      { month: "Jun 24", tokens: 9.97 },
      { month: "Jul 24", tokens: 10.32 },
      { month: "Aug 24", tokens: 10.65 },
      { month: "Sep 24", tokens: 10.99 },
      { month: "Oct 24", tokens: 11.33 },
      { month: "Nov 24", tokens: 11.66 },
      { month: "Dec 24", tokens: 12.00 },
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Dario_Amodei_at_TechCrunch_Disrupt_2023_01.jpg/330px-Dario_Amodei_at_TechCrunch_Disrupt_2023_01.jpg",
    logoUrl:
      "https://images.crunchbase.com/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/gudggzfh7mq5dajv9zld",
    color: "from-orange-800 to-amber-700",
    gradientId: "anthropicGradient",
    foundedYear: 2021,
    headquarters: "San Francisco, California, USA",
  },
];
