// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dakfcntliydkpzbmiurt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRha2ZjbnRsaXlka3B6Ym1pdXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzg2MDMsImV4cCI6MjA2MTg1NDYwM30.GYhEpPozR4qgD3yAJ60ikQTXfe-e6j59Iqd0mySHSq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);